<?xml version="1.0" encoding="utf-8"?><Database Name="QL_PHONG_TRO" Class="QL_PhongTroDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QQCBI9B\SQLEXPRESS;Initial Catalog=QL_PHONG_TRO;Integrated Security=True" SettingsObjectName="DataAndSupport.Properties.Settings" SettingsPropertyName="QL_PHONG_TROConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DICHVU_THEM" Member="DICHVU_THEMs">
    <Type Name="DICHVU_THEM">
      <Column Name="ID_DVT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAIDICHVU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TU_NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DEN_NGAY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHONG_DICHVU_THEM" Member="PHONG" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="LOAI_DICH_VU_DICHVU_THEM" Member="LOAI_DICH_VU" ThisKey="ID_LOAIDICHVU" OtherKey="ID_LOAIDICHVU" Type="LOAI_DICH_VU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUAN_LY" Member="QUAN_Lies">
    <Type Name="QUAN_LY">
      <Column Name="TAIKHOAN" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="PHANQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="ID_PHONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_LOAIPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="[_status]" Member="_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHONG_DICHVU_THEM" Member="DICHVU_THEMs" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="DICHVU_THEM" />
      <Association Name="PHONG_HOP_DONG" Member="HOP_DONGs" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="HOP_DONG" />
      <Association Name="PHONG_DV_Dien_Nuoc" Member="DV_Dien_Nuocs" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="DV_Dien_Nuoc" />
      <Association Name="PHONG_HOA_DON" Member="HOA_DONs" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="HOA_DON" />
      <Association Name="LOAI_PHONG_PHONG" Member="LOAI_PHONG" ThisKey="ID_LOAIPHONG" OtherKey="ID_LOAIPHONG" Type="LOAI_PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_DICH_VU" Member="LOAI_DICH_VUs">
    <Type Name="LOAI_DICH_VU">
      <Column Name="ID_LOAIDICHVU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDICHVU" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_status]" Member="_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAI_DICH_VU_DICHVU_THEM" Member="DICHVU_THEMs" ThisKey="ID_LOAIDICHVU" OtherKey="ID_LOAIDICHVU" Type="DICHVU_THEM" />
    </Type>
  </Table>
  <Table Name="dbo.HOP_DONG" Member="HOP_DONGs">
    <Type Name="HOP_DONG">
      <Column Name="ID_HOPDONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_KHACHHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENCOC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYTHUE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[_status]" Member="_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PHONG_HOP_DONG" Member="PHONG" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="KHACH_HANG_HOP_DONG" Member="KHACH_HANG" ThisKey="ID_KHACHHANG" OtherKey="ID_KHACHHANG" Type="KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DV_Dien_Nuoc" Member="DV_Dien_Nuocs">
    <Type Name="DV_Dien_Nuoc">
      <Column Name="ID_DNuoc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang_TT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CSM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHONG_DV_Dien_Nuoc" Member="PHONG" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACH_HANG" Member="KHACH_HANGs">
    <Type Name="KHACH_HANG">
      <Column Name="ID_KHACHHANG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENKHACHHANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="[_status]" Member="_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KHACH_HANG_HOP_DONG" Member="HOP_DONGs" ThisKey="ID_KHACHHANG" OtherKey="ID_KHACHHANG" Type="HOP_DONG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_PHONG" Member="LOAI_PHONGs">
    <Type Name="LOAI_PHONG">
      <Column Name="ID_LOAIPHONG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIAPHONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[_status]" Member="_status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LOAI_PHONG_PHONG" Member="PHONGs" ThisKey="ID_LOAIPHONG" OtherKey="ID_LOAIPHONG" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.HOA_DON" Member="HOA_DONs">
    <Type Name="HOA_DON">
      <Column Name="ID_HOADON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thang_TToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PHONG_HOA_DON" Member="PHONG" ThisKey="ID_PHONG" OtherKey="ID_PHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>